--  PDFVIEW0F Table for F4PDFVIEW Project 
--  Change then name of the SCHEMA (Library)
CREATE TABLE FAQ400/PDFVIEW0F ( 
	"ID" INTEGER GENERATED ALWAYS AS IDENTITY ( 
	START WITH 1 INCREMENT BY 1 
	NO MINVALUE NO MAXVALUE 
	NO CYCLE NO ORDER 
	CACHE 20 ) 
	, 
	RND INTEGER NOT NULL DEFAULT 0 , 
	PDF_PATH VARCHAR(256) CCSID 1208 NOT NULL DEFAULT '' , 
	VIEWSALLOWED FOR COLUMN VIEWS00001 INTEGER NOT NULL DEFAULT 1 , 
	VIEWS INTEGER NOT NULL DEFAULT 0 , 
	USERNAME VARCHAR(18) CCSID 280 GENERATED ALWAYS AS ( USER ) , 
	TS_INSERT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	TS_UPDATE TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL )   
	  
	RCDFMT PDFVIEW0F  ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON FAQ400/PDFVIEW0F TO PUBLIC WITH GRANT OPTION ; 
  

